---

- name: Configure Tomcat's server.xml
  become: true
  template:
    src: server.xml.j2
    dest: '{{ tomcat_dest }}/conf/server.xml'
  notify:
    - restart tomcat

- name: Configure Tomcat's tomcat-users.xml
  become: true
  template:
    src: tomcat-users.xml.j2
    dest: '{{ tomcat_dest }}/conf/tomcat-users.xml'
  notify:
    - restart tomcat

- name: Configure access to manager app from remote
  become: true
  template:
    src: manager.xml.j2
    dest: '{{ tomcat_dest }}/conf/Catalina/localhost/manager.xml'
  notify:
    - restart tomcat

- name: Configure access to manager app from remote
  become: true
  template:
    src: manager.xml.j2
    dest: '{{ tomcat_dest }}/conf/Catalina/localhost/manager.xml'
  notify:
    - restart tomcat

- name: Set java opts
  become: true
  template:
    src: setenv.sh.j2
    dest: '{{ tomcat_dest }}/bin/setenv.sh'
  notify:
    - restart tomcat