---

- name: Configure Tomcat's server.xml
  sudo: yes
  template:
    src: server.xml.j2
    dest: '{{ tomcat_dest }}/conf/server.xml'
  notify:
    - restart tomcat

- name: Configure Tomcat's tomcat-users.xml
  sudo: yes
  template:
    src: tomcat-users.xml.j2
    dest: '{{ tomcat_dest }}/conf/tomcat-users.xml'
  notify:
    - restart tomcat