---

- name: Install python-software-properties
  apt: name=python-software-properties state=installed update_cache=yes cache_valid_time=86400

- name: Install python-pycurl
  apt: name=python-pycurl state=installed

#- name: Add apt-key
#  apt_key: data="{{ lookup('file', '<key>.key') }}" state=present
#
#- name: Add repository
#  apt_repository: repo='{{ <tool>.deb.repo }}' state=present update_cache=yes
