---

- include: repo.yml

- include: dependencies_deb.yml
  when: ansible_os_family == "Debian"

- include: dependencies_redhat.yml
  when: ansible_os_family == "RedHat"

- include: install_deb.yml
  when: ansible_os_family == "Debian"

- include: install_redhat.yml
  when: ansible_os_family == "RedHat"

- include: config.yml
  notify:
    - restart tomcat

- include: service_deb.yml
  when: ansible_os_family == "Debian"
  notify:
    - restart tomcat