---
# handlers file for ansible-tomcat8

- name: restart tomcat
  sudo: yes
  service:
    name: tomcat8
    state: restarted
    enabled: yes

- name: reload tomcat config
  sudo: yes
  service:
    name: tomcat8
    state: reloaded
    enabled: yes