---
# handlers file for ansible-tomcat8

- name: restart tomcat
  become: true
  service:
    name: tomcat8
    state: restarted
    enabled: yes

- name: reload tomcat config
  become: true
  service:
    name: tomcat8
    state: reloaded
    enabled: yes